# Generated by Django 2.2.2 on 2019-07-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'normal_user'), (2, 'restaurant_1_admin'), (3, 'restaurant_2_admin'), (4, 'restaurant_3_admin'), (5, 'restaurant_4_admin'), (6, 'restaurant_5_admin'), (7, 'restaurant_6_admin'), (8, 'restaurant_7_admin'), (9, 'restaurant_8_admin'), (10, 'restaurant_9_admin'), (11, 'restaurant_10_admin'), (12, 'restaurant_11_admin'), (13, 'super_admin')], default=1),
        ),
    ]
