# Generated by Django 2.2.2 on 2019-07-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfooditem',
            name='orderfooditem_fooditem_name',
            field=models.CharField(default=5, max_length=500),
            preserve_default=False,
        ),
    ]
