# Generated by Django 2.2.2 on 2019-07-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_orderfooditem_orderfooditem_fooditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfooditem',
            name='orderfooditem_fooditem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderfooditem_fooditem_id', to='apis.FoodItem'),
        ),
        migrations.AlterField(
            model_name='orderfooditem',
            name='orderfooditem_fooditem_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
